version: 1.0.{build}
image:
- Ubuntu1804
- Visual Studio 2019
configuration: Release
clone_depth: 50

pull_requests:
  do_not_increment_build_number: true

#skip_branch_with_pr: true
skip_commits:
  files:
    - docs/*
    - media/*
    - LICENSE
    - mkdocs.yml
    - README.md
    - .travis.yml
    - .gitignore

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  clone_folder: C:\projects\easycaching\

  services:
  - docker
                
  before_build:
  - ps: docker pull redis  
  - ps: docker pull bitnami/memcached:latest
  - ps: docker run -p 6379:6379 --name redis6379 -d redis:latest
  - ps: docker run -p 6380:6379 --name redis6380 -d redis:latest
  - ps: docker run -p 6388:6379 --name redis6388 -d redis:latest
  - ps: docker run -p 11211:11211 --name memcached1 -d bitnami/memcached:latest
  - ps: docker run -p 11212:11211 --name memcached2 -d bitnami/memcached:latest
  - ps: docker ps -a
  - ps: dotnet tool install --global FlubuCore.GlobalTool --version 4.2.8

  build_script:
   - ps: flubu Rebuild.Server -apiKey=%api_key%
 
-
  matrix:
    only:
      - image: Ubuntu1804

  clone_folder: /home/appveyor/projects/easycaching

  services:
  - docker
    
  before_build:
  - sh: docker pull redis  
  - sh: docker pull memcached
  - sh: docker run -p 6379:6379 --name redis6379 -d redis:latest redis-server
  - sh: docker run -p 6380:6379 --name redis6380 -d redis:latest redis-server  
  - sh: docker run -p 6388:6379 --name redis6388 -d redis:latest redis-server  
  - sh: docker run -p 11211:11211 --name memcached1 -d memcached memcached -m 64 -c 2048
  - sh: docker run -p 11212:11211 --name memcached2 -d memcached memcached -m 64 -c 2048
  - sh: docker ps -a
  - sh: dotnet tool install --global FlubuCore.GlobalTool --version 4.2.8
  
  build_script:
  - sh: flubu Rebuild -s=build/BuildScript.cs
    
