site_name: EasyCaching
theme: readthedocs
repo_url: https://github.com/dotnetcore/EasyCaching

pages:
- Introduction: index.md
- Features : Features.md
- Caching Provider:
    - In-Memory : In-Memory.md
    - Redis : Redis.md
    - CSRedis: CSRedis.md
    - Memcached : Memcached.md
    - SQLite : SQLite.md
    - Hybird : Hybrid.md
    - Disk : Disk.md
    - LiteDB : LiteDB.md
    # - ProviderFactory : ProviderFactory.md
- Provider Factory:
    - Overview : FactoryOverview.md
    - EasyCachingProvider  : EasyCachingProvider.md
    - RedisCachingProvider : RedisCachingProvider.md
    - HybridCachingProvider  : HybridCachingProvider.md   
- Caching Interceptor:
    - Overview : InterceptorOverview.md
    - AspectCore : AspectCore.md
    - Castle : Castle.md
- Caching Serializer:
    - Overview : SerializerOverview.md
    - BinaryFormatter : BinaryFormatter.md
    - MessagePack : MessagePack.md
    - NewtonsoftJson : NewtonsoftJson.md
    - SystemTextJson : SystemTextJson.md
    - Protobuf : ProtoBuf.md
    
